elena_ovsyannikova/week5/day2/city_library/config/routes.rb
Rails.application.routes.draw do
  root :to => 'cities#index'
  get '/cities' => 'cities#index'
  get '/cities/new' => 'cities#new'
  post '/cities' => 'cities#create'
  get '/cities/:id' => 'cities#show', :as => 'city'
  get '/cities/:id/edit' => 'cities#edit', :as => 'city_edit'
  post '/cities/:id' => 'cities#update'
  delete '/cities/:id' => 'cities#destroy'






  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

elena_ovsyannikova/week5/day2/city_library/app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          primary key
#  name       :text
#  image      :text
#  population :float
#  square     :float
#  country    :text
#

class City < ActiveRecord::Base
end

elena_ovsyannikova/week5/day2/city_library/app/models/concerns/city.rb
class City < ActiveRecord::Base
end

elena_ovsyannikova/week5/day2/city_library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # skip_before_action :verify_authenticity_token # Only for handwritten forms.
end

elena_ovsyannikova/week5/day2/city_library/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find params[:id]
  end

  def new
  end

  def create
    city = City.new
    city.name= params[:name]
    city.image= params[:image]
    city.population= params[:population]
    city.square= params[:square]
    city.country= params[:country]
    city.save
    redirect_to city_path(city.id)
  end

  def edit
    @city = City.find params[:id]
  end

  def update
    city = City.find params[:id]
    city.name= params[:name]
    city.image= params[:image]
    city.population= params[:population]
    city.square= params[:square]
    city.country= params[:country]
    city.save
    redirect_to city_path(city.id)

  end

  def destroy
    city = City.find params[:id]
    city.destroy
    redirect_to cities_path

  end



end

elena_ovsyannikova/week5/day2/city_library/app/views/cities/edit.html.erb
<h1>Edit City</h1>

<form action="<%= city_path(@city.id) %>" method="post">
<label>Name: </label>
<input type="text" name="name" value="<%= @city.name %>" required>
<label>Image: </label>
<input type="url" name="image" value="<%= @city.image %>">
<label>Population: </label>
<input type="number" name="population" value="<%= @city.population %>">
<label>Square: </label>
<input type="number" name="square" value="<%= @city.square %>">
<label>Country: </label>
<input type="text" name="country" value="<%= @city.country %>">
<button>Edit city</button>

</form>

elena_ovsyannikova/week5/day2/city_library/app/views/cities/index.html.erb
<h1>All CITIES</<h1>
<% @cities.each do |city| %>
<p>
  <%= link_to city.name, city_path(city.id) %>
  has
  <%= pluralize city.population, 'person' %>.
</p>
<% end %>

elena_ovsyannikova/week5/day2/city_library/app/views/cities/new.html.erb
<h1>New city</h1>

<form action="<%= cities_path %>" method="post">
<label>Name: </label>
<input type="text" name="name" required>
<label>Image: </label>
<input type="url" name="image">
<label>Population: </label>
<input type="number" name="population">
<label>Square: </label>
<input type="number" name="square">
<label>Country: </label>
<input type="text" name="country">
<button>Create city</button>

</form>

elena_ovsyannikova/week5/day2/city_library/app/views/cities/show.html.erb
<h1><%= @city.name %></h1>


<ul>

  <li>Name: <%= @city.name %></li>
  <li>Population: <%= @city.population %></li>
  <li>Square: <%= @city.square %></li>
  <li>Country: <%= @city.country %></li>
</ul>

<%= image_tag @city.image, :class =>'feature'  if @city.image.present? %>

<div class="controls">
  <%= link_to 'Edit City', city_edit_path(@city.id), :class => 'control' %>
</div>
<div class="controls">
  <%= button_to 'Delete City', city_path(@city.id), :method => 'delete', :data => {:confirm => 'Are you sure?', :class => 'control'} %>

</div>