danny_ceccattini/week05/summits/config/routes.rb
Rails.application.routes.draw do
  root :to => 'mountains#home'
  get '/mountains' => 'mountains#index'
  # CREATING
  get 'mountains/new' => 'mountains#new'
  post '/mountains' => 'mountains#create'
  # SHOWING
  get 'mountains/:id' => 'mountains#show', :as => 'mountain'
  #EDITING
  get 'mountains/:id/edit' => 'mountains#edit', :as => 'mountain_edit'
  post 'mountains/:id' => 'mountains#update'
  # DESTROY
  delete 'mountains/:id' => 'mountains#destroy'

end

danny_ceccattini/week05/summits/app/models/mountain.rb
# == Schema Information
#
# Table name: mountains
#
#  id        :integer          primary key
#  name      :text
#  location  :text
#  height    :integer
#  image     :text
#  white_man :text
#

class Mountain < ActiveRecord::Base
end

danny_ceccattini/week05/summits/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token # ONLY FOR HAND WRITTEN FORMS
end

danny_ceccattini/week05/summits/app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  def home
  end

  def index
    @mountains = Mountain.all
  end

  def show
    @mountain = Mountain.find params[:id]
  end

  def new
  end

  def create
    mountain = Mountain.new
    mountain.name = params[:name]
    mountain.location = params[:location]
    mountain.height = params[:height]
    mountain.image = params[:image]
    mountain.white_man = params[:white_man]
    mountain.save
    redirect_to mountain_path(mountain.id)
  end

  def edit
    @mountain = Mountain.find params[:id]
  end

  def update
    mountain = Mountain.find params[:id]
    mountain.name = params[:name]
    mountain.location = params[:location]
    mountain.height = params[:height]
    mountain.image = params[:image]
    mountain.white_man = params[:white_man]
    mountain.save
    redirect_to mountain_path(mountain.id)
  end

  def destroy
    mountain = Mountain.find params[:id]
    mountain.destroy
    redirect_to mountains_path
  end
end

danny_ceccattini/week05/summits/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>High Places</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <%= link_to 'Home', root_path %>
        <%= link_to 'All The High Places', mountains_path %>
        <%= link_to 'Another High Place?', mountains_new_path %>
      </nav>
      <h1>LOOK UP!</h1>
      <%= yield %>
    </div>
  </body>
</html>