sean_mccusker/homework/week05/08-rails/moma/config/routes.rb
Rails.application.routes.draw do
  root :to => 'works#index'
  resources :artists
  resources :works
end

sean_mccusker/homework/week05/08-rails/moma/app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :works
end

sean_mccusker/homework/week05/08-rails/moma/app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :artist, :optional => true
end

sean_mccusker/homework/week05/08-rails/moma/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find params[:id]
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create artist_params
    redirect_to artist
  end

  def edit
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]
    artist.update artist_params
    redirect_to artist
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path
  end

  private
  # Strong params
  def artist_params
    # White list of parameters which are permitted
    params.require(:artist).permit(:name, :nationality, :dob, :period, :image)
  end
end

sean_mccusker/homework/week05/08-rails/moma/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def show
    @work = Work.find params[:id]
  end

  def new
    @work = Work.new
  end

  def create
    work = Work.create work_params
    redirect_to work
  end

  def edit
    @work = Work.find params[:id]
  end

  def update
    work = Work.find params[:id]
    work.update work_params
    redirect_to work
  end

  def destroy
    work = Work.find params[:id]
    work.destroy
    redirect_to works_path
  end

  private
  def work_params
    params.require(:work).permit(:title, :year, :medium, :style, :image, :artist_id)
  end
end

sean_mccusker/homework/week05/08-rails/moma/app/views/works/_form.html.erb
<%= form_for @work do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true %>
  <%= f.label :year %>
  <%= f.text_field :year %>
  <%= f.label :medium %>
  <%= f.text_field :medium %>
  <%= f.label :style %>
  <%= f.text_field :style %>
  <%= f.label :image %>
  <%= f.url_field :image, :required => true %>
  <%= f.label :artist_id %>
  <%= f.select :artist_id, Artist.pluck(:name, :id), :include_blank => true %>
  <%= f.submit %>
<% end %>

sean_mccusker/homework/week05/08-rails/moma/app/views/works/edit.html.erb
<h2>Edit Work</h2>

<%= render :partial => 'form' %>

sean_mccusker/homework/week05/08-rails/moma/app/views/works/index.html.erb
<h2>All Works</h2>
<% @works.each do |work| %>
  <%= link_to image_tag(work.image, :class => 'thumb'), work %>
<% end %>

sean_mccusker/homework/week05/08-rails/moma/app/views/works/new.html.erb
<h2>New Work</h2>

<%= render :partial => 'form' %>

sean_mccusker/homework/week05/08-rails/moma/app/views/works/show.html.erb
<h2><%= @work.title %></h2>
<%= image_tag @work.image, :alt => @work.title, :class => 'feature' %>
<ul>
  <li>Title: <%= @work.title %></li>
  <% if @work.artist.present? %>
    <li>Artist: <%= link_to @work.artist.name, @work.artist %></li>
  <% end %>
  <li>Year: <%= @work.year %></li>
  <li>Medium: <%= @work.medium %></li>
  <li>Style: <%= @work.style %></li>
</ul>

<div class="controls">
  <%= link_to 'Edit work', edit_work_path(@work) %>
  <%= link_to 'Delete work', @work, :method => 'delete' %>
</div>