shouyi_wang/week05/tuesday/mountains/config/routes.rb
Rails.application.routes.draw do
  root :to => 'mountains#index'
  get '/mountains' => 'mountains#index'
  get '/mountains/new' => 'mountains#new'
  post '/mountains' => 'mountains#create'
  get '/mountains/:id' => 'mountains#show', :as => 'mountain'
  get '/mountains/:id/edit' => 'mountains#edit', :as => 'mountain_edit'
  post '/mountains/:id' => 'mountains#update'
  delete '/mountains/:id' => 'mountains#destroy'
end

shouyi_wang/week05/tuesday/mountains/app/models/mountain.rb
class Mountain < ActiveRecord::Base
end

shouyi_wang/week05/tuesday/mountains/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

shouyi_wang/week05/tuesday/mountains/app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  def index
    @mountains = Mountain.all
  end

  def show
    @mountain = Mountain.find params[:id]
  end

  def create
    mountain = Mountain.new
    mountain.name = params[:name]
    mountain.image = params[:image]
    mountain.height = params[:height]
    mountain.location = params[:location]
    mountain.save
    redirect_to mountain_path(mountain.id)
  end

  def edit
    @mountain = Mountain.find params[:id]
  end

  def update
    mountain = Mountain.find params[:id]
    mountain.name = params[:name]
    mountain.image = params[:image]
    mountain.height = params[:height]
    mountain.location = params[:location]
    mountain.save
    redirect_to mountain_path(mountain.id)
  end

  def destroy
    mountain = Mountain.find params[:id]
    mountain.destroy
    redirect_to mountains_path
  end


end

shouyi_wang/week05/tuesday/mountains/app/views/mountains/edit.html.erb
<h1>Edit Mountain</h1>

<form action="<%= mountain_path(@mountain.id) %>" method="post">
  <label>Name:</label>
  <input type="text" name="name" value="<%= @mountain.name %>" required>
  <label>Image:</label>
  <input type="url" name="image" value="<%= @mountain.image %>">
  <label>Height:</label>
  <input type="number" name="height" value="<%= @mountain.height %>">
  <label>Location:</label>
  <input type="text" name="location" value="<%= @mountain.location %>">

  <button>Update Mountain</button>
</form>

shouyi_wang/week05/tuesday/mountains/app/views/mountains/index.html.erb
<h1>All Mountains</h1>

<% @mountains.each do |mountain| %>
  <p>
    The height of
    <%= link_to mountain.name, mountain_path(mountain.id) %>
    is
    <%=  mountain.height %>.
  </p>
<% end %>

shouyi_wang/week05/tuesday/mountains/app/views/mountains/new.html.erb
<h1>New Mountain</h1>

<form action="<%= mountains_path %>" method="post">
  <label>Name:</label>
  <input type="text" name="name" required>
  <label>Image:</label>
  <input type="url" name="image">
  <label>Height:</label>
  <input type="number" name="height">
  <label>Location:</label>
  <input type="text" name="location">

  <button>Create Mountain</button>
</form>

shouyi_wang/week05/tuesday/mountains/app/views/mountains/show.html.erb
<h1><%= @mountain.name %></h1>

<%= image_tag @mountain.image, :class => 'feature' if @mountain.image.present? %>

<ul>
  <li>Name: <%= @mountain.name %></li>
  <li title= "<%= @mountain.height %>">Height: <%= number_to_human @mountain.height %> meters</li>
  <li>Location: <%= @mountain.location %></li>
</ul>

<div class="controls">
  <%= link_to 'Edit mountain', mountain_edit_path(@mountain.id) %>
  <%= button_to 'Delete mountain', mountain_path(@mountain.id), :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
</div>